arch: arm64: configs: changes after uprev FCM version 6
ERROR: files are incompatible: Runtime info and framework compatibility matrix are incompatib
le: No compatible kernel requirement found (kernel FCM version = 6).
For kernel requirements at matrix level 6, Kernel config errors:
    For config CONFIG_ANDROID_LOW_MEMORY_KILLER, value = y but required n
    Missing config CONFIG_CRYPTO_CHACHA20POLY1305
    Missing config CONFIG_SONY_FF
    Missing config CONFIG_XFRM_MIGRATE
: Success